# Generated by Django 3.2 on 2021-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_type', models.CharField(choices=[('client', 'کاربر'), ('admin', 'ادمین')], default='client', max_length=6, verbose_name='نوع حساب')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس ')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'اکانت کاربر',
                'verbose_name_plural': 'اکانت\u200c کاربرها',
            },
        ),
    ]
