# Generated by Django 3.2 on 2021-04-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'اکانت', 'verbose_name_plural': 'اکانت\u200cها'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('client', 'کاربر'), ('admin', 'ادمین')], default='client', max_length=10),
        ),
    ]
