# Generated by Django 3.2 on 2021-04-16 14:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210416_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=256)),
                ('token_expiration', models.DateTimeField(default=datetime.datetime(2021, 4, 16, 16, 52, 29, 660499))),
                ('account_type', models.CharField(choices=[('client', 'کاربر'), ('admin', 'ادمین')], default='client', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='زمان ساخت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر'),
        ),
    ]
