# Generated by Django 3.2 on 2021-04-16 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210416_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 16, 52, 49, 8251)),
        ),
    ]
