# Generated by Django 3.2 on 2021-04-16 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_accesstoken_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 17, 31, 25, 326137)),
        ),
    ]
