# Generated by Django 3.2 on 2021-04-16 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_accesstoken_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='username',
            field=models.CharField(default='salam', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 17, 32, 52, 388520)),
        ),
    ]
